const CODEFORCES_CONTEST_URL = "https://codeforces.com/api/contest.list";
const ATCODER_CONTEST_URL = "https://atcoder.jp/contests/";
const LEETCODE_CONTEST_URL = "https://leetcode.com/contest/";
const CODECHEF_CONTEST_URL = "https://www.codechef.com/contests";

const CODEFORCES_REQUEST_TIMEOUT = 2000;
const ATCODER_REQUEST_TIMEOUT = 2000;
const LEETCODE_REQUEST_TIMEOUT = 2000;

export {
  CODEFORCES_CONTEST_URL,
  ATCODER_CONTEST_URL,
  LEETCODE_CONTEST_URL,
  CODECHEF_CONTEST_URL,
  CODEFORCES_REQUEST_TIMEOUT,
  ATCODER_REQUEST_TIMEOUT,
  LEETCODE_REQUEST_TIMEOUT,
};
